# Generated by Django 2.1.1 on 2018-09-30 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_player_turn', models.BooleanField(default=True)),
                ('action1_object_id', models.PositiveIntegerField()),
                ('action2_object_id', models.PositiveIntegerField()),
                ('action1_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action1', to='contenttypes.ContentType')),
                ('action2_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action2', to='contenttypes.ContentType')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_arm', models.BooleanField(default=False)),
                ('right_arm', models.BooleanField(default=False)),
                ('body', models.BooleanField(default=False)),
                ('left_leg', models.BooleanField(default=False)),
                ('right_leg', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
